/*
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.dsl.formatting2

import org.eclipse.xtext.formatting.IIndentationInformation

class KukulkanIndentationInformation implements IIndentationInformation  {
	
	override getIndentString() {
		return '    '
	}
	
}
